### ISSUE TITLE
curator.py error

### ISSUE THREAD

**Issue by zhipengliux** [gaolabtools/scNanoGPS#13]
commond: 
python ~/soft/scNanoGPS/curator.py -t 50 --ref_genome ~/ref/ssc/Sus_scrofa.Sscrofa11.1.dna.toplevel.fa
error: 
Mapping reads for each individual cell barcode ...
rm: cannot remove 'tmp/GAAATGACACTCTGCT.unsorted.bam': No such file or directory
[E::hts_open_format] Failed to open file "tmp/GAAATGACACTCTGCT.minimap2.bam" : No such file or directory
Traceback (most recent call last):
  File "/home/data/fuli14/soft/scNanoGPS/curator.py", line 175, in <module>
    seq_dict = curator_io.build_read_seq_dict(os.path.join(options.tmp_dir, fq_pref) + ".minimap2.bam")
  File "/home/data/fuli14/soft/scNanoGPS/curator_core/curator_io.py", line 193, in build_read_seq_dict
    bam_f = pysam.AlignmentFile(bam_name, "rb")
  File "pysam/libcalignmentfile.pyx", line 748, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 947, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `tmp/GAAATGACACTCTGCT.minimap2.bam`: No such file or directory

**Comment by zhipengliux** [comment]
Sorry about that! The error focus on samtools. Because lost some "lib.so" use "conda install samtools". Need to "conda install samtools=1.9"
