### ISSUE TITLE
Error during scanner 

### ISSUE THREAD

**Issue by BenneyMRArgue** [gaolabtools/scNanoGPS#19]
Hi! Thanks for developing this amazing tool. 

I am running into this issue when trying to run scanner on my fastq files. 

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/software/python-anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/software/python-anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/mra7674/scNanoGPS/scanner_core/searching_core.py", line 128, in ten_nano_workflow
    h3_ps_res = precise_search(na_seq_header, options.adaptor_three_p, 0, options.scan_region, options.scoring_threshold, options.dp_penalty)
  File "/home/mra7674/scNanoGPS/scanner_core/searching_core.py", line 58, in precise_search
    seqA  = str(alignment_res[0].seqA)
AttributeError: 'tuple' object has no attribute 'seqA'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mra7674/scNanoGPS/scanner.py", line 70, in <module>
    tmp_data = pool.map(partial(searching_core.ten_nano_workflow, options = options), batch_data)
  File "/software/python-anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/software/python-anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AttributeError: 'tuple' object has no attribute 'seqA'
```

Here is a screenshot of what my fastq file looks like. Could you help us? 
![image](https://github.com/gaolabtools/scNanoGPS/assets/129222227/b7c66fe8-a8c1-49ee-9b82-79b16e881c97)

Thank you!

**Comment by shiauck** [comment]
Hi,

The error message is regarding to biopython SeqIO module.
I've tried using your fastq running scanner.py, but there's no error in my side.
Could you please share me "pip3 list" result to check the version of biopython ?
Thanks.

Regards,
Cheng-Kai

P.S.
The following is the result copied from my terminal:

```
> python3 scanner.py -i source/ --debug_mode 1

1
header: GTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACCTTTTCTGTTGGTGCTGATATTGCAAGCAGTGGTATCAACGCAGAGTACTTTTTTTTTTTTTTTT
polyT:                                                                                      TTTTTTTTTTTT

tail:   ACTTGCCTGTCGCTCTATCTTCCTACACGACGCTCTTCCGATCTTAAGTGCCAATTCCTTGGTTGCTCACTTTCTTATATGGGGAGAGGCACCCCGGACA

Processed 1 reads, Time elapse: 0 : 0 : 0.10

Processed total 1 reads.
Found 0 reads have 3'-adaptor + polyT.
Detecting rate: 0.00%
```

**Comment by BenneyMRArgue** [comment]
Thanks for looking into this. The pip3 list result shows biopython version as 1.83.

Here's the full list: 
Package             Version
------------------- ------------
autograd            1.6.2
autograd-gamma      0.5.0
biopython           1.83
contourpy           1.2.0
cycler              0.12.1
Distance            0.1.3
fonttools           4.47.2
formulaic           1.0.1
future              0.18.3
importlib-resources 6.1.1
interface-meta      1.3.0
kiwisolver          1.4.5
lifelines           0.28.0
liqa                1.3.4
matplotlib          3.8.2
mkl-fft             1.3.1
mkl-random          1.2.2
mkl-service         2.4.0
numpy               1.22.4
packaging           23.2
pandas              2.1.4
pillow              10.2.0
pip                 23.3.1
pyparsing           3.1.1
pysam               0.22.0
python-dateutil     2.8.2
pytz                2023.3.post1
scipy               1.6.2
seaborn             0.13.1
setuptools          68.2.2
six                 1.16.0
typing_extensions   4.9.0
tzdata              2023.4
wheel               0.41.2
wrapt               1.16.0
zipp                3.17.0

Thanks,
-Benney

**Comment by shiauck** [comment]
Hi Benney,

I tried to create a virtual environment under Anaconda with python3.7(according to your error log), and python3.8.
But I failed to install the python modules with the version you listed.

I tried to create python3.9 virtual environment, but a partial of modules could not be installed with the listed version.

Please try to create a new environment with the latest version of python and modules.
The following is the terminal log I did:

The command for installing environment:
```
> ~/anaconda/bin/conda create -n test_env python=3.9
```
The prompt I got:
```
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.11.1
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0



## Package Plan ##

  environment location: ~/anaconda3/envs/test_env

  added / updated specs:
    - python=3.9


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge 
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_gnu 
  bzip2              conda-forge/linux-64::bzip2-1.0.8-hd590300_5 
  ca-certificates    conda-forge/linux-64::ca-certificates-2023.11.17-hbcca054_0 
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.40-h41732ed_0 
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5 
  libgcc-ng          conda-forge/linux-64::libgcc-ng-13.2.0-h807b86a_5 
  libgomp            conda-forge/linux-64::libgomp-13.2.0-h807b86a_5 
  libnsl             conda-forge/linux-64::libnsl-2.0.1-hd590300_0 
  libsqlite          conda-forge/linux-64::libsqlite-3.44.2-h2797004_0 
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0 
  libxcrypt          conda-forge/linux-64::libxcrypt-4.4.36-hd590300_1 
  libzlib            conda-forge/linux-64::libzlib-1.2.13-hd590300_5 
  ncurses            conda-forge/linux-64::ncurses-6.4-h59595ed_2 
  openssl            conda-forge/linux-64::openssl-3.2.1-hd590300_0 
  pip                conda-forge/noarch::pip-23.3.2-pyhd8ed1ab_0 
  python             conda-forge/linux-64::python-3.9.18-h0755675_1_cpython 
  readline           conda-forge/linux-64::readline-8.2-h8228510_1 
  setuptools         conda-forge/noarch::setuptools-69.0.3-pyhd8ed1ab_0 
  tk                 conda-forge/linux-64::tk-8.6.13-noxft_h4845f30_101 
  tzdata             conda-forge/noarch::tzdata-2023d-h0c530f3_0 
  wheel              conda-forge/noarch::wheel-0.42.0-pyhd8ed1ab_0 
  xz                 conda-forge/linux-64::xz-5.2.6-h166bdaf_0 


Proceed ([y]/n)? y


Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```
Then I activated the environment by:
```
source ~/anaconda/bin/activate test_env
```
Installing modules for scNanoGPS:
```
pip3 install -r scNanoGPS/requirements.txt
```
The installation log looks like:
```
Collecting biopython (from -r requirements.txt (line 1))
  Using cached biopython-1.83-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
Collecting distance (from -r requirements.txt (line 2))
  Using cached Distance-0.1.3-py3-none-any.whl
Collecting liqa (from -r requirements.txt (line 3))
  Using cached liqa-1.3.4-py3-none-any.whl.metadata (2.2 kB)
Collecting matplotlib (from -r requirements.txt (line 4))
  Using cached matplotlib-3.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting pandas (from -r requirements.txt (line 5))
  Downloading pandas-2.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting pysam (from -r requirements.txt (line 6))
  Using cached pysam-0.22.0.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting seaborn (from -r requirements.txt (line 7))
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Collecting numpy (from biopython->-r requirements.txt (line 1))
  Using cached numpy-1.26.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting lifelines (from liqa->-r requirements.txt (line 3))
  Using cached lifelines-0.28.0-py3-none-any.whl.metadata (3.2 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 4))
  Using cached contourpy-1.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 4))
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements.txt (line 4))
  Using cached fonttools-4.47.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (157 kB)
Collecting kiwisolver>=1.3.1 (from matplotlib->-r requirements.txt (line 4))
  Using cached kiwisolver-1.4.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl.metadata (6.4 kB)
Collecting packaging>=20.0 (from matplotlib->-r requirements.txt (line 4))
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting pillow>=8 (from matplotlib->-r requirements.txt (line 4))
  Using cached pillow-10.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (9.7 kB)
Collecting pyparsing>=2.3.1 (from matplotlib->-r requirements.txt (line 4))
  Using cached pyparsing-3.1.1-py3-none-any.whl.metadata (5.1 kB)
Collecting python-dateutil>=2.7 (from matplotlib->-r requirements.txt (line 4))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting importlib-resources>=3.2.0 (from matplotlib->-r requirements.txt (line 4))
  Using cached importlib_resources-6.1.1-py3-none-any.whl.metadata (4.1 kB)
Collecting pytz>=2020.1 (from pandas->-r requirements.txt (line 5))
  Using cached pytz-2023.4-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->-r requirements.txt (line 5))
  Using cached tzdata-2023.4-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting zipp>=3.1.0 (from importlib-resources>=3.2.0->matplotlib->-r requirements.txt (line 4))
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->-r requirements.txt (line 4))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting scipy>=1.2.0 (from lifelines->liqa->-r requirements.txt (line 3))
  Downloading scipy-1.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 3.8 MB/s eta 0:00:00
Collecting autograd>=1.5 (from lifelines->liqa->-r requirements.txt (line 3))
  Using cached autograd-1.6.2-py3-none-any.whl.metadata (706 bytes)
Collecting autograd-gamma>=0.3 (from lifelines->liqa->-r requirements.txt (line 3))
  Using cached autograd_gamma-0.5.0-py3-none-any.whl
Collecting formulaic>=0.2.2 (from lifelines->liqa->-r requirements.txt (line 3))
  Using cached formulaic-1.0.1-py3-none-any.whl.metadata (6.1 kB)
Collecting future>=0.15.2 (from autograd>=1.5->lifelines->liqa->-r requirements.txt (line 3))
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... done
Collecting interface-meta>=1.2.0 (from formulaic>=0.2.2->lifelines->liqa->-r requirements.txt (line 3))
  Using cached interface_meta-1.3.0-py3-none-any.whl (14 kB)
Collecting typing-extensions>=4.2.0 (from formulaic>=0.2.2->lifelines->liqa->-r requirements.txt (line 3))
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting wrapt>=1.0 (from formulaic>=0.2.2->lifelines->liqa->-r requirements.txt (line 3))
  Using cached wrapt-1.16.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Downloading biopython-1.83-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 34.3 MB/s eta 0:00:00
Downloading liqa-1.3.4-py3-none-any.whl (32 kB)
Using cached matplotlib-3.8.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Downloading pandas-2.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 91.7 MB/s eta 0:00:00
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 69.2 MB/s eta 0:00:00
Using cached contourpy-1.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (310 kB)
Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Using cached fonttools-4.47.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Using cached importlib_resources-6.1.1-py3-none-any.whl (33 kB)
Using cached kiwisolver-1.4.5-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Using cached numpy-1.26.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached pillow-10.2.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.4 MB)
Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
Downloading pytz-2023.4-py2.py3-none-any.whl (506 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 506.5/506.5 kB 66.7 MB/s eta 0:00:00
Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 40.7 MB/s eta 0:00:00
Downloading lifelines-0.28.0-py3-none-any.whl (349 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 349.2/349.2 kB 53.5 MB/s eta 0:00:00
Downloading autograd-1.6.2-py3-none-any.whl (49 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.3/49.3 kB 10.9 MB/s eta 0:00:00
Downloading formulaic-1.0.1-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.2/94.2 kB 30.4 MB/s eta 0:00:00
Downloading scipy-1.12.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.5/38.5 MB 48.8 MB/s eta 0:00:00
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Downloading wrapt-1.16.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (80 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.1/80.1 kB 22.5 MB/s eta 0:00:00
Building wheels for collected packages: pysam, future
  Building wheel for pysam (pyproject.toml) ... done
  Created wheel for pysam: filename=pysam-0.22.0-cp39-cp39-linux_x86_64.whl size=8465209 sha256=7add808d3e80660407040d22c7acb84e2f52e1ae32c1840eb73c856500001b76
  Stored in directory: .cache/pip/wheels/0f/4a/1e/667e44d2281914fc3f223519ba8f7e606fa98752509f01a37b
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.3-py3-none-any.whl size=492024 sha256=42212ebb92ae9d00a769aee40ceec9099a0080695c4ae7c7510d0ec0eeb213bb
  Stored in directory: .cache/pip/wheels/bf/5d/6a/2e53874f7ec4e2bede522385439531fafec8fafe005b5c3d1b
Successfully built pysam future
Installing collected packages: pytz, distance, zipp, wrapt, tzdata, typing-extensions, six, pysam, pyparsing, pillow, packaging, numpy, kiwisolver, interface-meta, future, fonttools, cycler, scipy, python-dateutil, importlib-resources, contourpy, biopython, autograd, pandas, matplotlib, autograd-gamma, seaborn, formulaic, lifelines, liqa
Successfully installed autograd-1.6.2 autograd-gamma-0.5.0 biopython-1.83 contourpy-1.2.0 cycler-0.12.1 distance-0.1.3 fonttools-4.47.2 formulaic-1.0.1 future-0.18.3 importlib-resources-6.1.1 interface-meta-1.3.0 kiwisolver-1.4.5 lifelines-0.28.0 liqa-1.3.4 matplotlib-3.8.2 numpy-1.26.3 packaging-23.2 pandas-2.2.0 pillow-10.2.0 pyparsing-3.1.1 pysam-0.22.0 python-dateutil-2.8.2 pytz-2023.4 scipy-1.12.0 seaborn-0.13.2 six-1.16.0 typing-extensions-4.9.0 tzdata-2023.4 wrapt-1.16.0 zipp-3.17.0
```
The python3 modules I installed under the new environment:
```
> pip3 list
Package             Version
------------------- -------
autograd            1.6.2
autograd-gamma      0.5.0
biopython           1.83
contourpy           1.2.0
cycler              0.12.1
Distance            0.1.3
fonttools           4.47.2
formulaic           1.0.1
future              0.18.3
importlib-resources 6.1.1
interface-meta      1.3.0
kiwisolver          1.4.5
lifelines           0.28.0
liqa                1.3.4
matplotlib          3.8.2
numpy               1.26.3
packaging           23.2
pandas              2.2.0
pillow              10.2.0
pip                 23.3.2
pyparsing           3.1.1
pysam               0.22.0
python-dateutil     2.8.2
pytz                2023.4
scipy               1.12.0
seaborn             0.13.2
setuptools          69.0.3
six                 1.16.0
typing_extensions   4.9.0
tzdata              2023.4
wheel               0.42.0
wrapt               1.16.0
zipp                3.17.0
```
Then I'm running scNanoGPS against the read you provided (I stored it as a file at: source/test.fq) :
```
> python3 scNanoGPS/scanner.py -i source/test.fq --debug_mode 1

Processing file name: source/test.fq
1
~/anaconda3/envs/test_env/lib/python3.9/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
header: GTTAAGACTACTTTCTGCCTTTGCGAGAACAGCACCTTTTCTGTTGGTGCTGATATTGCAAGCAGTGGTATCAACGCAGAGTACTTTTTTTTTTTTTTTT
polyT:                                                                                      TTTTTTTTTTTT

tail:   ACTTGCCTGTCGCTCTATCTTCCTACACGACGCTCTTCCGATCTTAAGTGCCAATTCCTTGGTTGCTCACTTTCTTATATGGGGAGAGGCACCCCGGACA

Processed 1 reads, Time elapse: 0 : 0 : 0.07

Processed total 1 reads.
Found 0 reads have 3'-adaptor + polyT.
Detecting rate: 0.00%
```

Hope this helps.

Regards,
Cheng-Kai

**Comment by BenneyMRArgue** [comment]
Creating the environment with python 3.9 resolved the issue, thanks so much!

**Comment by shiauck** [comment]
Sweet ! I'm glad to help.
