### ISSUE TITLE
Cannot set up scNanoGPS environment

### ISSUE THREAD

**Issue by JThomasWatson** [gaolabtools/scNanoGPS#30]
Hello,

When following the environment creation instructions, the command `pip3 install -r requirements.txt` fails with something related to pysam. The error text says the system cannot find the file specified, and that the problem likely does not originate from pip. This is on a brand new windows 10 machine using the anaconda powershell to run the commands. I'm using python 3.12.3. The full output is below:

```
(scNanoGPS) PS D:\scNanoGPS> pip3 install -r requirements.txt
Collecting biopython (from -r requirements.txt (line 1))
  Using cached biopython-1.83-cp312-cp312-win_amd64.whl.metadata (13 kB)
Collecting distance (from -r requirements.txt (line 2))
  Using cached Distance-0.1.3-py3-none-any.whl
Collecting liqa (from -r requirements.txt (line 3))
  Using cached liqa-1.3.4-py3-none-any.whl.metadata (2.2 kB)
Collecting matplotlib (from -r requirements.txt (line 4))
  Using cached matplotlib-3.8.4-cp312-cp312-win_amd64.whl.metadata (5.9 kB)
Collecting pandas (from -r requirements.txt (line 5))
  Using cached pandas-2.2.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pysam (from -r requirements.txt (line 6))
  Using cached pysam-0.22.1.tar.gz (4.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      # pysam: cython is available - using cythonize if necessary
      # pysam: htslib mode is shared
      # pysam: HTSLIB_CONFIGURE_OPTIONS=None
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      '.' is not recognized as an internal or external command,
      operable program or batch file.
      # pysam: htslib configure options: None
      Traceback (most recent call last):
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ward12369user2\AppData\Local\Temp\pip-build-env-9yrhlcwm\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ward12369user2\AppData\Local\Temp\pip-build-env-9yrhlcwm\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\ward12369user2\AppData\Local\Temp\pip-build-env-9yrhlcwm\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\ward12369user2\AppData\Local\Temp\pip-build-env-9yrhlcwm\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 437, in <module>
        File "<string>", line 81, in run_make_print_config
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\subprocess.py", line 466, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\subprocess.py", line 548, in run
          with Popen(*popenargs, **kwargs) as process:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\ward12369user2\AppData\Local\miniconda3\envs\scNanoGPS\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip 

```

**Comment by shiauck** [comment]
Hi,

Please check [this](https://stackoverflow.com/questions/60197890/why-does-installing-pysam-python-package-fail) to see whether it's helpful.
Thanks.

Regards,
Cheng-Kai

**Comment by JThomasWatson** [comment]
Hi, Cheng-Kai. Thank you! I didn't realize samtools required a non-windows OS. I ended up making a Docker container to get around that.
